spring:
  datasource:
    url: jdbc:mysql://45.126.122.26:3306/stalls_erp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: fuhuiwang
    password: fuhuiwang@2018
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.github.wenql.stallserp: debug